# версия синтаксиса Docker Compose
version: '3.8'

# секция в которой определяются сервисы, необходимы для работы приложения
services:
  # определение сервиса бэкэнда
  backend:
    # перед запуском сервиса нужно дождаться когда будет запущен сервис бд
    depends_on:
      - db
    # собираю образ для этого сервиса из заданного каталога, который содержит Dockerfile
    build: ./
    # указываю название для образа сервиса при создании
    image: book-shop
    # определение портов контейнера
    ports:
      - "8000:8000"
    # указываю файл, который содержит переменные окружения
    env_file:
      - .env
    # команды, которые будут выполняться при запуске контейнера
    command: ["./wait-for-it.sh", "db:5432", "--timeout=60", "--", "./book-shop"]

  # определение сервиса бд
  db:
    # указывает Docker, чтобы контейнер автоматически перезапускался в случае его остановки
    restart: always
    # указывает на то, что для этого сервиса будет взят образ postgres:latest из Docker Hub
    image: postgres:latest
    # определение портов контейнера
    ports:
      - "5432:5432"
    # указываю файл, который содержит переменные окружения
    env_file:
      - .env
    # переношу из директории файлы в свою локальную, для сохранения данных в бд между перезапусками контейнера
    volumes:
      - ./pkg/repository/data:/var/lib/postgresql/data